model:
  base_learning_rate: 4.5e-06
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    cond_stage_config: __is_unconditional__
    #first_stage_key: image
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1024
        block_size: 256
        n_layer: 12 #24
        n_head: 16
        n_embd: 832 #1664
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/2023-03-30T13-19-11_custom_vqgan/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.vqperceptual.DummyLoss

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 30
    num_workers: 4
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: 1_train.txt
        size: 208
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: 1_test.txt
        size: 208